### ISSUE TITLE
Delete or cancel a ride /api/rides/:userID/:rideID - API Support

### ISSUE THREAD

**Issue by EvelynL09** [rise-summer/team2-studentRideSharing#24]
- status field for each ride
    - status 0: regular ride (will show up in search results)
    - status 1: completed (available in user's ride history, won't be searched)
    - status 2: cancelled (available in user's ride history, won't be searched)
  
- DELETE /api/rides/:userID/:rideID for rides with no pending/confirmed passengers
    - 200 deleted succesfully
    - 400 
        - rideID not valid objectID
        - no such ride with rideID and status of 0
- PUT /api/rides/cancel/:userID/:rideID
    - 200 successfully change the status from 0 to 1
    - 400 
        - if there's no such a ride or 
        - the status of the ride is not 0
        - the request time is too closed to the ride's time (within 24 hours?)

**Comment by EvelynL09** [comment]
@micheyale Under what scenario will this request be made? e.g. User > My Rides > click the delete button next to one of the posted rides? Is there any restriction for such an operation? (e.g. a user cannot delete a ride with any confirmed passengers)

**Comment by micheyale** [comment]
@EvelynL09 Yes so User > MyRides > click the delete button next to the ride. Idk if we should put a restriction such as user cannot delete a ride with confirmed passengers. Some drivers might have a last-minute change of plans and therefore would need to delete the ride. But I think for now that would be a good restriction, so lets set a restriction where a driver would not be able to delete a ride with confirmed passengers. I will discuss with Valeska on what she thinks.

**Comment by micheyale** [comment]
@EvelynL09 so updates on restriction, Valeska prefers Driver to be able to cancel a ride with confirmed passengers on it. However, is there a way we can keep track of the each driver's cancellation? For example, instead of deleting the ride, can we change the status of the ride by having another attribute in Rides Table called "Cancelled". It would be good to be able to keep track of how many canceled rides a driver has so we can flag them if they have too many canceled rides. Or we can have another attribute in User's table called "Cancelled rides" to store all the ride_id they have canceled. 

After a driver canceled a ride, the riders will be notified of the canceled rides. Another thing that we can restrict is that drivers cant cancel rides that are too close to the date itself. For example, drivers cant cancel the ride 24 hrs before the ride.

**Comment by EvelynL09** [comment]
I think we can add a status field to each ride. And we can have something like:
status 0: regular ride (will show up in search results)
status 1: cancelled (available in user's ride history, won't be searched)
status 2: completed (available in user's ride history, won't be searched)

But if a driver wants to cancel a ride that doesn't have any pending/confirmed passengers, we can allow them to delete it completely.
